### ISSUE TITLE
status/firehose doesn't work

### ISSUE THREAD

**Issue by abhididdigi** [AvianFlu/ntwitter#122]
When I try to GET using status/firehouse, this it the error I get, Is drinking from Firehose supported? Please do look into this:

This is the call:

```
twit.stream('statuses/firehose', function(stream) {
      stream.on('data', function (data) {
        console.log(data);
      });
    });
```

This is the error:

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at ClientRequest.<anonymous> (/home/abhididdigi/Node Projects/TwitterStreaming/node_modules/ntwitter/lib/twitter.js:251:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1669:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1564:20)
    at CleartextStream.read [as _read] (tls.js:502:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
```

**Comment by imshashank** [comment]
same here.. I just couldnt get it . why is it giving error !!

**Comment by ghost** [comment]
Did you guys work with this feature before and it just gave you this error or is this your first try and have no idea whether it's supported or not? 
I haven't check this feature by my own because I need an account that's been approved by Twitter for accessing to the firehose. That's why I'm curious to see if this is supported or not.
tnx

**Comment by imshashank** [comment]
Hey, it was being caused by wrong twitter API keys. Once I did them again, everything was fixed. Thanks for the help :-)

**Comment by ghost** [comment]
Hey there, thanks for the reply :)

**Comment by rajnmithun** [comment]
i am getting the same error, i checked my credentials as below where i get success

```
twit.verifyCredentials(function (err, data) {
if(err){
    console.log("***error***");
    console.log(err);
} else{
    console.log("---success---")
    console.log(data);
}
```

});

also i tried doing 

```
 twit.search('nodejs OR #node', {}, function(err, data) {
if(err){
    console.log("***error***");
    console.log(err);
} else{
    console.log("---success---")
    //console.log(data);
}
});
```

i am getting 

{ [Error: HTTP Error 410: Gone]
  statusCode: 410,
  data: '{"errors": [{"message": "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code": 68}]}' }

can you please let me know what am i missing.
