### ISSUE TITLE
Unspecified 'error' event

### ISSUE THREAD

**Issue by EwanValentine** [AvianFlu/ntwitter#146]
I get the following error intermittently, sometimes it works, but most the time I get this.

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
  at TypeError (<anonymous>:null:null)
  at EventEmitter.emit (events.js:74:15)
  at ClientRequest.<anonymous> (/Users/username/Development/App/node_modules/ntwitter/lib/twitter.js:251:14)
  at ClientRequest.EventEmitter.emit (events.js:95:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
  at CleartextStream.read [as _read] (tls.js:511:12)
  at CleartextStream.Readable.read (_stream_readable.js:320:10)
  at EncryptedStream.write [as _write] (tls.js:366:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:582:24)
  at flow (_stream_readable.js:591:7)
  at Socket.pipeOnReadable (_stream_readable.js:623:5)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:407:10)
  at emitReadable (_stream_readable.js:403:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

**Comment by ciruz** [comment]
sync your server clock, this helped me with the same error.

```
yum install ntp
chkconfig ntpd on
ntpdate pool.ntp.org
/etc/init.d/ntpd start
```

**Comment by freekot** [comment]
I get the same error. Syncing clock did not help.
