### ISSUE TITLE
Search example in README.md fails.

### ISSUE THREAD

**Issue by ghost** [AvianFlu/ntwitter#45]
The search example in `README.md` fails when you try to run it.

``` javascript
twit.search('nodejs OR #node', function(err, data) {
  console.log(data);
});
```

It should, instead be:

``` javascript
twit.search('nodejs OR #node', {}, function(err, data) {
  console.log(data);
});
```

`Twitter.prototype.search` starting on line `155` of `twitter.js` will set `params` to `null` without the empty object, and will then attempt to run that `null` through the `util.merge` function with the query parameters. This results in the following error:

```
TypeError: Cannot set property 'q' of null
  at Object.merge (/path/to/node_modules/ntwitter/lib/utils.js:9:18)
  at Twitter.search (/path/to/node_modules/ntwitter/lib/twitter.js:167:18)
  at Object.<anonymous> (/path/to/scratch.js:55:8)
```

**Comment by jvanaert** [comment]
thanks !
